
[sdl]
fullscreen=false
output=opengl

[dosbox]
machine=svga_s3
captures=capture

[cpu]
core=auto
cycles=auto

[mixer]
nosound=false
rate=44100

[midi]
mpu401=intelligent
mididevice=default

[sblaster]
sbtype=sbpro2
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=44100

[speaker]
pcspeaker=false

[autoexec]
@echo off
mount c ..
c:
SIMFARM.EXE
exit
